// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGMZ4AW_8-hEM23Jt_SqpDcV2zapzIMBU',
    appId: '1:487959600071:web:6c900ea2baba00260e97e2',
    messagingSenderId: '487959600071',
    projectId: 'asistenciaapp-9c3de',
    authDomain: 'asistenciaapp-9c3de.firebaseapp.com',
    storageBucket: 'asistenciaapp-9c3de.appspot.com',
    measurementId: 'G-7SJ17Z8Z72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDl7pM1gkTLsqAnxSZfVPHdpJi_Ky5tqw',
    appId: '1:487959600071:android:d43af665555038800e97e2',
    messagingSenderId: '487959600071',
    projectId: 'asistenciaapp-9c3de',
    storageBucket: 'asistenciaapp-9c3de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkyuli84Vy2nXJQJNZ-er4T5Cem-H26l8',
    appId: '1:487959600071:ios:656e996acd9580a80e97e2',
    messagingSenderId: '487959600071',
    projectId: 'asistenciaapp-9c3de',
    storageBucket: 'asistenciaapp-9c3de.appspot.com',
    iosBundleId: 'com.example.asistenciaManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkyuli84Vy2nXJQJNZ-er4T5Cem-H26l8',
    appId: '1:487959600071:ios:656e996acd9580a80e97e2',
    messagingSenderId: '487959600071',
    projectId: 'asistenciaapp-9c3de',
    storageBucket: 'asistenciaapp-9c3de.appspot.com',
    iosBundleId: 'com.example.asistenciaManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGMZ4AW_8-hEM23Jt_SqpDcV2zapzIMBU',
    appId: '1:487959600071:web:ebae3bc4ed1930d80e97e2',
    messagingSenderId: '487959600071',
    projectId: 'asistenciaapp-9c3de',
    authDomain: 'asistenciaapp-9c3de.firebaseapp.com',
    storageBucket: 'asistenciaapp-9c3de.appspot.com',
    measurementId: 'G-MHXN60VQ96',
  );
}
